#! /bin/bash
#
# Browses the directory structure generated by readpst to create 
# a local folders one for Thunderbird import.
#
# Usage: thunpst.sh [dir]
#
# 	dir:	directory to browse and convert (curdir by default)
#
# This file is released under a GPL v3 licence
#
#     This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

thun=$(echo $0)
if [ $# -gt 2 ]; then
	echo Usage: thunpst dir
	exit -1
fi
if [ -d "$1" ]; then
	cd "$1"
	dir=$(pwd)
else
	echo thunpst: "$1" does not exist
	exit -2
fi

directories=$(ls -l|grep ^d|grep -v \.sbd|sed "s/.*:..\ //g"|tr ' ' ·)
for file in $directories; do
	fich=$(echo "$file"|tr · ' ')
	dir="$fich".sbd
	mv "$fich" "$dir"
	mv "$dir"/mbox "$fich"
	if [ $(ls -l "$dir" |wc -l) -gt 1 ]; then
		"$thun" "$dir"
	else
		rmdir "$dir"
	fi
done
